age = int(input('Enter your age: '))
if age == 69: print('Nice')   
elif age >= 60: print('You are old')
elif age >= 30: print("You are middle aged")
elif age >= 18: print('You are an adult')
else: print('You are not and adult')